service: hello-world

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
